baseURL = "https://johan237.github.io/website.github.io/"
languageCode = "en-us"
title = "Johan personal website"
theme="archie"
copyright = "Â© Johan Kemmegne Tchassem"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=true
	subtitle = "Johan K. T. personal website "
	mathjax = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/johan237"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/johan_tchassem/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
